#!/usr/bin/env bash


key=$1
value=$2
yt_url="https://www.youtube.com"
opts="-f mp4 \
--download-archive ids.txt \
--write-description \
--write-info-json \
--write-annotations \
--write-sub \
--write-thumbnail\
"

if [[ $key == "video_id" ]]; then
  cd downloads && yt-dlp $opts "$yt_url/watch?v=$value"
elif [[ $key == "playlist_id" ]]; then
  cd downloads && yt-dlp $opts "$yt_url/playlist?list=$value"
elif [[ $key == "video_title" ]]; then
  cd downloads && yt-dlp $opts "ytsearch:$value"
fi
