#!/bin/bash


Opt=$1

function App () {
    if ! [ -d ./venv ]; then
        virtualenv venv && source ./venv/bin/activate && pip install -r ./requirements.txt
    elif [[ -f ./requirements.txt ]]; then
        source ./venv/bin/activate && pip install -r ./requirements.txt
    fi
}


if [ "$Opt" == "app" ]; then
  ( App )
fi
